# Application basics
spring.application.name=card-management-system
server.port=9090
encryption.secret=c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4
bank.bin=242004

# DB configuration
spring.datasource.url=jdbc:postgresql://cm-db:5432/card-main
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT configuration
jwt.access.secret-key=QIoy+51enERMHx5BzA5bjaFljUsceMxUuHDTwawBK2I=
jwt.access.duration=1800000
jwt.refresh.duration=2592000000

# Logging configuration
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE
logging.level.ru.maverick=DEBUG


